{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    {{- include "sample-helm-app.labels" . | nindent 4 }}
    environment: {{ .Values.global.environment }}
{{- end }} 