# Production environment values for sample-helm-app

global:
  environment: production

app:
  name: sample-helm-app
  image:
    tag: "1.25-alpine"
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

deployment:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
